# Generated by Django 2.0.1 on 2018-01-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_inventory', '0003_auto_20180117_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data przychodu i względnie rozchodu'),
        ),
    ]
