# Generated by Django 2.0.1 on 2018-01-17 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items_inventory', '0004_auto_20180117_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Operacja')),
                ('old_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='wcześniejsza wartość')),
                ('new_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='nowa wartość')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='ignore', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
