# Generated by Django 2.0.1 on 2018-01-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_inventory', '0006_auto_20180117_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='incoming_value',
            field=models.CharField(blank=True, default='1', max_length=255, verbose_name='Wartość przychodu'),
        ),
        migrations.AlterField(
            model_name='record',
            name='number_of_incoming',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Ilość przychodu'),
        ),
        migrations.AlterField(
            model_name='record',
            name='number_of_outgoing',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Ilość rozchodu'),
        ),
        migrations.AlterField(
            model_name='record',
            name='number_result',
            field=models.IntegerField(blank=True, default=0, verbose_name='Stan Ilości'),
        ),
        migrations.AlterField(
            model_name='record',
            name='outgoing_value',
            field=models.CharField(blank=True, default='1', max_length=255, verbose_name='Wartość rozchodu'),
        ),
        migrations.AlterField(
            model_name='record',
            name='value_result',
            field=models.CharField(blank=True, default='0', max_length=255, verbose_name='Stan Wartości'),
        ),
    ]
